spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/vision-guard-server-websocket-db
    username: postgres
    password: "138294"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true